### ISSUE TITLE
Make sign in sign up page responsive

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [web-contribution-DWOC/Team-Builder#27]
Make the sign in and sign page fully responsive.

**Comment by GauravGupta993** [comment]
Hi @Naresh-chandanbatve, I would like to work on this issue. Please assign this issue to me.

**Comment by Naresh-chandanbatve** [comment]
sure @GauravGupta993 
go for it

**Comment by Nikhil-IITG** [comment]
@Naresh-chandanbatve Can you please assign this issue to me

**Comment by GauravGupta993** [comment]
> @Naresh-chandanbatve Can you please assign this issue to me

Sorry, but I have already started working on this issue and will have it completed by today.

**Comment by Albert-2** [comment]
hey @Naresh-chandanbatve
I would very much like to work on this issue as I'm quite good at responsive designs. 
can you please assign me the same under codepeak'23
THANK YOU FOR CONSIDERING.... :)

**Comment by GauravGupta993** [comment]
> hey @Naresh-chandanbatve I would very much like to work on this issue as I'm quite good at responsive designs. can you please assign me the same under codepeak'23 THANK YOU FOR CONSIDERING.... :)

I am already working on this issue and the work is already done.
