### ISSUE TITLE
imrpove the ui of add idea page

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [web-contribution-DWOC/Team-Builder#3]
imrpove the ui of add idea page
it must be matching with theme of team info page

Directories :
chat page : /views/Team-Builder-Dashboard/idea-form/index.html
team info page : /views/Team-Builder-Dashboard/team-info-page/team-info-page.html

**Comment by SattyamSamania** [comment]
Can I work on this issue?

**Comment by Naresh-chandanbatve** [comment]
@SattyamSamania 
Go for it

**Comment by Nupoor10** [comment]
Hello, can I work on this? @Naresh-chandanbatve

**Comment by Naresh-chandanbatve** [comment]
sure @Nupoor10 
go for it
