### ISSUE TITLE
Improve the ui of idea info page

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [web-contribution-DWOC/Team-Builder#7]
imrpove the ui of idea info page 
it must be matching with theme of team info page

Directories :
idea ingo page : /views/Team-Builder-Dashboard/idea-info-page/idea-info.html
team info page : /views/Team-Builder-Dashboard/team-info-page/team-info-page.html

**Comment by Trisha-tech** [comment]
Hi @Naresh-chandanbatve 
I want to work on this issue under KWOC'22. Can you please assign this to me?

**Comment by Naresh-chandanbatve** [comment]
@Trisha-tech 
Go for it.
