### ISSUE TITLE
develop a page of what team builder is and how to use it

### ISSUE THREAD

**Issue by Naresh-chandanbatve** [web-contribution-DWOC/Team-Builder#8]
develop a page of what team builder is 
how to use it
features that it provides
and link it on the log in page

with text 'what is team builder?'

**Comment by Ghat0tkach** [comment]
May i work on this issue?

**Comment by Naresh-chandanbatve** [comment]
@Ghat0tkach 
Go for it

**Comment by Ghat0tkach** [comment]
@Naresh-chandanbatve  I think we can close this as completed

**Comment by Ghat0tkach** [comment]
Can you close this issue? Please?🥲
